FROM ubuntu:latest
LABEL maintainer="charlesrocket"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    sudo \
    ansible \
    apt-transport-https \
    ca-certificates-java \
    curl \
    init \
    && rm -rf /var/lib/apt/lists/*

RUN dpkg-divert --local --rename --add /sbin/udevadm && ln -s /bin/true /sbin/udevadm

RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

CMD ["/sbin/init"]
