---
name: Build

on:
  pull_request:
  push:
  schedule:
    - cron: "10 1 * * 0"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - alpine
          - fedora
          - rockylinux

    steps:
      - uses: actions/checkout@v3

      - name: Test building image
        run: docker build -t test-ansible -f Dockerfile.${{ matrix.distro }}-latest .

      - name: Run the built image
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro test-ansible

      - name: Test Ansible
        run: docker exec --tty test-container env TERM=xterm ansible --version

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/trunk'
    steps:
      - uses: actions/checkout@v3

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ matrix.distro }}
          dockerfile: Dockerfile.${{ matrix.distro }}-latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
