---
name: Test

on:
  pull_request:
  push:
  schedule:
    - cron: "35 1 * * 0"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - alpine
          - arch
          - debian
          - fedora
          - opensuse
          - rocky
          - ubuntu

    steps:
      - uses: actions/checkout@v3

      - name: Test building image
        run: |
          cd ${{ matrix.distro }}
          docker build -t test-ansible .

      - name: Run the built image
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro test-ansible

      - name: Test Ansible
        run: docker exec --tty test-container env TERM=xterm ansible --version
