---
name: Test

on:
  pull_request:
  push:
  schedule:
    - cron: "35 1 * * 0"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - alpine
          - debian
          - rocky

    steps:
      - uses: actions/checkout@v3

      - name: Test building image
        run: |
          cd ${{ matrix.distro }}
          docker build -t test-ansible .

      - name: Run the built image
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro test-ansible

      - name: Test Ansible
        run: docker exec --tty test-container env TERM=xterm ansible --version

  push:
    name: Push
    needs: test
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/trunk') || github.event_name == 'schedule' }}
    strategy:
      matrix:
        distro:
          - alpine
          - debian
          - rocky

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        run: |
          cd ${{ matrix.distro }}
          docker build \
            --no-cache \
            --rm \
            --tag=charlesrocket/${{ matrix.distro }}:latest \
            .

      - name: Push to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u charlesrocket --password-stdin
          docker tag charlesrocket/${{ matrix.distro }}:latest docker.pkg.github.com/charlesrocket/ansible-containers/${{ matrix.distro }}:latest
          docker push docker.pkg.github.com/charlesrocket/ansible-containers/${{ matrix.distro }}:latest
