---
name: Test

on:
  pull_request:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - alpine
          - debian
          - fedora
          - opensuse
          - rockylinux
          - ubuntu

    steps:
      - uses: actions/checkout@v3

      - name: Test building image
        run: docker build -t test-ansible -f Dockerfile.${{ matrix.distro }}-latest .

      - name: Run the built image
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro test-ansible

      - name: Test Ansible
        run: docker exec --tty test-container env TERM=xterm ansible --version
